#!/bin/bash
cd $HOME
wget https://raw.githubusercontent.com/kirbycope/PiCasePrintings/main/oled.py
wget https://raw.githubusercontent.com/kirbycope/PiCasePrintings/main/oled.service
sudo cp oled.service /etc/systemd/system/oled.service
sudo systemctl enable oled.service
sudo apt-get install python-smbus python3-smbus python-dev python3-dev i2c-tools
sudo pip3 install Adafruit-PureIO
sudo pip3 install Adafruit_BBIO
sudo python3 -m pip install --upgrade pip setuptools wheel
sudo pip3 install Adafruit-SSD1306
sudo apt-get install build-essential python-pip python-dev python-smbus git
git clone https://github.com/adafruit/Adafruit_Python_GPIO.git
cd Adafruit_Python_GPIO
sudo python3 setup.py install
cd $HOME
wget https://raw.githubusercontent.com/kirbycope/PiCasePrintings/main/led.py
wget https://raw.githubusercontent.com/kirbycope/PiCasePrintings/main/led.service
sudo cp led.service /etc/systemd/system/led.service
sudo systemctl enable led.service
sudo apt-get install gcc make build-essential python-dev git
git clone https://github.com/jgarff/rpi_ws281x
cd rpi_ws281x/python
sudo python3 setup.py build
sudo python3 setup.py install
sudo pip3 install adafruit-circuitpython-neopixel
cd $HOME
wget https://raw.githubusercontent.com/kirbycope/PiCasePrintings/main/pwr.py
wget https://raw.githubusercontent.com/kirbycope/PiCasePrintings/main/pwr.service
sudo cp led.service /etc/systemd/system/pwr.service
sudo systemctl enable pwr.service
