#!/bin/bash
cd $HOME
wget -O https://raw.githubusercontent.com/kirbycope/PiCasePrintings/main/oled.service
sudo cp oled.service /etc/systemd/system/oled.service
sudo systemctl enable oled.service
wget -O https://raw.githubusercontent.com/kirbycope/PiCasePrintings/main/oled.py
wget -O https://raw.githubusercontent.com/kirbycope/PiCasePrintings/main/type_writer.ttf
sudo apt-get install python-smbus python3-smbus python-dev python3-dev i2c-tools
sudo pip3 install Adafruit-PureIO
sudo pip3 install Adafruit_BBIO
sudo python3 -m pip install --upgrade pip setuptools wheel
sudo pip3 install Adafruit-SSD1306
sudo apt-get install build-essential python-pip python-dev python-smbus git
git clone https://github.com/adafruit/Adafruit_Python_GPIO.git
cd Adafruit_Python_GPIO
sudo python3 setup.py install
